#!/usr/bin/env python3
"""Generate the three Arcade-SandScrp .mra files (sandscrp parent, sandscrpa,
sandscrpb clones) from ONE table transcribed from mame/src/mame/kaneko/
sandscrp.cpp, and, from the same table, the hardware-sim ioctl stream and
the reference-sim $readmemh images -- so the .mra, the stream the hardware
testbench replays and the images the reference sim reads can never disagree
about where a region lives (NMK16 lesson 4.A.3: one source, several outputs).

    python3 tools/gen_sandscrp_mra.py                 # releases/*.mra (+ _alternatives)
    python3 tools/gen_sandscrp_mra.py --ioctl [set]   # sim/rtl/sandscrp/roms/<set>_ioctl.bin
    python3 tools/gen_sandscrp_mra.py --simroms [set] # sim/rtl/sandscrp/roms/<set>_{maincpu,audiocpu,sprites,view2,oki}.hex
    python3 tools/gen_sandscrp_mra.py --check         # off-board load model: rebuild every .mra's
                                                      # stream from its own <part>/<interleave> list and
                                                      # compare it against the core's fixed base table
                                                      # and against tools/mk_ioctl_stream.py's output
then
    python3 tools/gen_hiscore_mra.py mame/plugins/hiscore/hiscore.dat
    python3 tools/gen_cheats_mra.py  ~/Downloads/cheat0279/cheat
    python3 tools/gen_autofire_mra.py

SDRAM layout (rtl/sandscrp/sandscrp_core.sv must use these exact bases):
    maincpu   0x000000  0x080000  ROM_LOAD16_BYTE pair, streamed with the ODD-offset
                                  file on even stream bytes (map="01") -- the NMK16
                                  convention rom_cache_n's byte-parity word rebuild
                                  expects (even stream byte = low byte of the 68000 word)
    audiocpu  0x080000  0x020000  plain
    sprites   0x0A0000  0x100000  plain, two files (or ss502.ic16 alone)
    view2     0x1A0000  0x100000  ROM_LOAD16_BYTE pair streamed in MAME MEMORY ORDER
                                  (even-offset file 3.ic33 map="01"): the tile decoder
                                  is byte-wise and reads MAME's region layout with no ^1;
                                  sandscrpb's ss501.ic30 is that exact byte sequence
                                  (verified 2026-09-19: ss501 == interleave(3.ic33, 4.ic32)
                                  and ss502 == 5.ic16 + 6.ic17), so both sets stream the
                                  same bytes through the same RTL path
    oki       0x2A0000  0x040000  plain
    end       0x2E0000
"""
import os, subprocess, sys, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RELEASES = os.path.join(ROOT, "releases")
ROMDIR = os.path.join(ROOT, "mame_roms")
SIMROMS = os.path.join(ROOT, "sim", "rtl", "sandscrp", "roms")

# region name -> (base, size). The core's constants; --check proves the .mra agrees.
BASES = [("maincpu", 0x000000, 0x080000), ("audiocpu", 0x080000, 0x020000), ("sprites", 0x0A0000, 0x100000),
         ("view2", 0x1A0000, 0x100000), ("oki", 0x2A0000, 0x040000)]
END = 0x2E0000

# ROM_START blocks. 'pair' = (even-offset file, odd-offset file) as MAME loads them.
PARENT_ROMS = dict(
    audiocpu=[("8.ic51", "6f3e9db1")],
    sprites=[("5.ic16", "9bb675f6"), ("6.ic17", "7df2f219")],
    view2_pair=(("3.ic33", "adf20fa0"), ("4.ic32", "b9222ff2")),
    oki=[("7.ic55", "9870ab12")],
)
SETS = [
    dict(setname="sandscrp", desc="Sand Scorpion", zip="sandscrp.zip", parent=None,
         main_pair=(("11.bin", "9b24ab40"), ("12.bin", "ad12caee")), **PARENT_ROMS),
    dict(setname="sandscrpa", desc="Sand Scorpion (Earlier)", zip="sandscrpa.zip|sandscrp.zip", parent="sandscrp",
         main_pair=(("1.ic4", "c0943ae2"), ("2.ic5", "6a8e0012")), **PARENT_ROMS),
    dict(setname="sandscrpb", desc="Kuai Da Shizi Huangdi (China?, Revised Hardware)", zip="sandscrpb.zip|sandscrp.zip", parent="sandscrp",
         main_pair=(("11.ic4", "80020cab"), ("12.ic5", "8df1d42f")),
         audiocpu=PARENT_ROMS["audiocpu"], sprites=[("ss502.ic16", "d8012ebb")],
         view2_single=[("ss501.ic30", "0cf9f99d")], oki=PARENT_ROMS["oki"]),
]

HEADER = '''<!--
  {desc} -- FACE 1992, MAME kaneko/sandscrp.cpp ({setname}). {origin}
  Generated by tools/gen_sandscrp_mra.py; ROM part order is the core's fixed
  SDRAM layout (see that script's header): maincpu @0x000000 (68000 pair, odd
  file on even stream bytes for the byte-parity word rebuild), audiocpu
  @0x080000, sprites @0x0A0000, view2 @0x1A0000 (pair streamed in MAME memory
  order: the tile decoder is byte-wise), oki @0x2A0000.
  <switches> byte 0 = DSW1 (SW1), byte 1 = DSW2 (SW2): these two bytes feed the
  YM2203's port A/B inputs -- on this board the Z80 reads the DIPs through the
  sound chip and reports them to the 68000 over the sound latch. Byte 2 is not
  a DIP; bit 6 of it is the hidden Autofire-menu unlock (tools/gen_autofire_mra.py).
-->
'''
BODY = '''<misterromdescription>
  <name>{desc}</name>
  <mratimestamp>202609190000</mratimestamp>
  <mameversion>0289</mameversion>
  <setname>{setname}</setname>
  <year>1992</year>
  <manufacturer>Face</manufacturer>
  <category>Shooter</category>
  <rbf>SandScrp</rbf>

  <!-- ROT90 in sandscrp.cpp (a vertical game). -->
  <rotation>{rotation}</rotation>

  <!-- DSW1 default 0xEF (3 lives, 3 bombs, Normal, 200K/500K), DSW2 0xFF
       (1C/1C, Flip off, Continue on, Demo Sounds on, Service off).
       ids are in bit-value order (value 0 first). -->
  <switches default="EF,FF,00">
    <dip bits="0,1"   name="Lives" ids="5,2,1,3"/>
    <dip bits="2,3"   name="Bombs" ids="5,2,1,3"/>
    <dip bits="4,5"   name="Difficulty" ids="Hardest,Hard,Normal,Easy"/>
    <dip bits="6,7"   name="Bonus Life" ids="1000K/3000K,500K/1000K,100K/300K,200K/500K"/>
    <dip bits="8,11"  name="Coinage" ids="Free_Play,8C_3C,5C_3C,3C_2C,2C_3C,1C_6C,1C_5C,1C_4C,1C_3C,1C_2C,6C_1C,5C_1C,4C_1C,3C_1C,2C_1C,1C_1C"/>
    <dip bits="12"    name="Flip Screen" ids="On,Off"/>
    <dip bits="13"    name="Allow Continue" ids="Off,On"/>
    <dip bits="14"    name="Demo Sounds" ids="Off,On"/>
    <dip bits="15"    name="Service Mode" ids="On,Off"/>
  </switches>

  <!-- Five entries, positionally the core's CONF_STR J1 list: Shot, Bomb,
       Button 3 (plain fire while Autofire is on), Start, Coin. -->
  <buttons names="Shot,Bomb,Button 3,Start,Coin" default="Y,B,A,Start,R"/>

  <rom index="0" zip="{zip}" md5="none">
{parts}  </rom>
</misterromdescription>
'''


def part(name, crc, indent="    ", attrs=""):
    return f'{indent}<part crc="{crc}" name="{name}"{attrs}/>\n'


def parts_xml(s):
    """The <rom index="0"> body, in SDRAM order."""
    out = ""
    (ev, ev_crc), (od, od_crc) = s["main_pair"]
    out += "    <!-- maincpu 0x080000 @ 0x000000: 68000 pair, odd-offset file first (map=01) -->\n"
    out += '    <interleave output="16">\n' + part(od, od_crc, "      ", ' map="01"') + part(ev, ev_crc, "      ", ' map="10"') + "    </interleave>\n"
    out += "    <!-- audiocpu 0x020000 @ 0x080000 -->\n" + "".join(part(n, c) for n, c in s["audiocpu"])
    out += "    <!-- sprites 0x100000 @ 0x0A0000 -->\n" + "".join(part(n, c) for n, c in s["sprites"])
    if "view2_pair" in s:
        (ev, ev_crc), (od, od_crc) = s["view2_pair"]
        out += "    <!-- view2 0x100000 @ 0x1A0000: pair in MAME memory order, even-offset file first (map=01) -->\n"
        out += '    <interleave output="16">\n' + part(ev, ev_crc, "      ", ' map="01"') + part(od, od_crc, "      ", ' map="10"') + "    </interleave>\n"
    else:
        out += "    <!-- view2 0x100000 @ 0x1A0000: single mask ROM, already in memory order -->\n" + "".join(part(n, c) for n, c in s["view2_single"])
    out += "    <!-- oki 0x040000 @ 0x2A0000 -->\n" + "".join(part(n, c) for n, c in s["oki"])
    return out


def mra_path(s):
    fn = s["desc"].replace("/", " - ").replace("?", "") + ".mra"   # '?' is illegal on exFAT
    if s["parent"]:
        return os.path.join(RELEASES, "_alternatives", "_" + SETS[0]["desc"], fn)
    return os.path.join(RELEASES, fn)


def write_mra(s):
    origin = "Parent set." if not s["parent"] else f"Clone of {s['parent']}; files shared with the parent are looked up in {s['parent']}.zip."
    text = HEADER.format(origin=origin, **s) + BODY.format(parts=parts_xml(s), rotation=ROTATION, **s)
    p = mra_path(s)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(p, ROOT))


# MiSTer <rotation>: kept as one constant so it can be corrected in one place once
# confirmed on the board against a MAME screenshot (M5). NMK16 shipped 1 for ROT270.
ROTATION = 1


# ---------------------------------------------------------------- load model
def zips_for(s):
    return [zipfile.ZipFile(os.path.join(ROMDIR, z)) for z in s["zip"].split("|")]


def read_member(zips, name, crc):
    for z in zips:
        try:
            info = z.getinfo(name)
        except KeyError:
            continue
        if info.CRC != int(crc, 16):
            raise SystemExit(f"{name}: zip CRC {info.CRC:08x} != table {crc}")
        return z.read(name)
    raise SystemExit(f"{name} not found in {[z.filename for z in zips]}")


def mra_stream(s):
    """Replay the .mra loader on the table: a literal model of <part> and
    <interleave output=16 map=..> (map is read right to left: the rightmost
    digit is output byte 0; digit k = byte k (1-based) of that part)."""
    zips = zips_for(s)
    buf = bytearray()
    regions = {}

    def plain(names):
        for n, c in names:
            buf.extend(read_member(zips, n, c))

    def interleave(parts):  # [(name, crc, map)]
        datas = [(read_member(zips, n, c), m) for n, c, m in parts]
        n = len(datas[0][0])
        out = bytearray(2 * n)
        for data, m in datas:
            assert len(data) == n and len(m) == 2
            for outbyte in range(2):
                digit = int(m[1 - outbyte])
                if digit:
                    out[outbyte::2] = data  # each part contributes its single byte stream
        buf.extend(out)

    (ev, evc), (od, odc) = s["main_pair"]
    regions["maincpu"] = len(buf); interleave([(od, odc, "01"), (ev, evc, "10")])
    regions["audiocpu"] = len(buf); plain(s["audiocpu"])
    regions["sprites"] = len(buf); plain(s["sprites"])
    regions["view2"] = len(buf)
    if "view2_pair" in s:
        (ev, evc), (od, odc) = s["view2_pair"]; interleave([(ev, evc, "01"), (od, odc, "10")])
    else:
        plain(s["view2_single"])
    regions["oki"] = len(buf); plain(s["oki"])
    return bytes(buf), regions


def check():
    ok = True
    ref = None
    for s in SETS:
        stream, regions = mra_stream(s)
        for name, base, size in BASES:
            if regions[name] != base:
                print(f"{s['setname']}: {name} lands at {regions[name]:#08x}, core expects {base:#08x}"); ok = False
        if len(stream) != END:
            print(f"{s['setname']}: stream is {len(stream):#x} bytes, core expects {END:#x}"); ok = False
        # word view of the 68000 region must equal MAME's big-endian program words
        zips = zips_for(s)
        (ev, evc), (od, odc) = s["main_pair"]
        e, o = read_member(zips, ev, evc), read_member(zips, od, odc)
        for i in (0, 1, 2, 3, 0x1000, 0x3ffff):
            w = stream[2 * i] | (stream[2 * i + 1] << 8)       # core: even stream byte = low byte
            if w != ((e[i] << 8) | o[i]):
                print(f"{s['setname']}: 68000 word {i:#x} = {w:04x}, MAME {(e[i] << 8) | o[i]:04x}"); ok = False
        # gfx/sound regions must be byte-identical across the three sets
        tail = stream[BASES[1][1]:]
        if ref is None:
            ref = tail
        elif tail != ref:
            print(f"{s['setname']}: audiocpu..oki bytes differ from the parent's"); ok = False
        # independent implementation: tools/mk_ioctl_stream.py's lo+hi syntax
        out = os.path.join(SIMROMS, f"{s['setname']}_ioctl_check.bin")
        os.makedirs(SIMROMS, exist_ok=True)
        args = [sys.executable, os.path.join(ROOT, "tools", "mk_ioctl_stream.py")]
        for z in s["zip"].split("|"):
            args += ["--zip", os.path.join(ROMDIR, z)]
        v2 = (f"{s['view2_pair'][0][0]}+{s['view2_pair'][1][0]}" if "view2_pair" in s else s["view2_single"][0][0])
        args += ["--region", f"0x000000:{od}+{ev}", "--region", f"0x080000:{','.join(n for n, _ in s['audiocpu'])}",
                 "--region", f"0x0A0000:{','.join(n for n, _ in s['sprites'])}", "--region", f"0x1A0000:{v2}",
                 "--region", f"0x2A0000:{','.join(n for n, _ in s['oki'])}", "--out", out]
        subprocess.run(args, check=True, stdout=subprocess.DEVNULL)
        other = open(out, "rb").read(); os.remove(out)
        if other != stream:
            print(f"{s['setname']}: mk_ioctl_stream.py disagrees with the .mra model"); ok = False
        print(f"{s['setname']}: stream {len(stream):#x} bytes, regions {' '.join(f'{k}@{v:#08x}' for k, v in regions.items())} -> {'OK' if ok else 'MISMATCH'}")
    return ok


def ioctl(setnames):
    os.makedirs(SIMROMS, exist_ok=True)
    for s in SETS:
        if s["setname"] in setnames:
            stream, _ = mra_stream(s)
            p = os.path.join(SIMROMS, f"{s['setname']}_ioctl.bin")
            open(p, "wb").write(stream); print(f"wrote {os.path.relpath(p, ROOT)} ({len(stream)} bytes)")


def simroms(setnames):
    """$readmemh images for the HW_ROMS=0 reference sim, one per region, straight from the table."""
    os.makedirs(SIMROMS, exist_ok=True)
    for s in SETS:
        if s["setname"] not in setnames:
            continue
        zips = zips_for(s)
        (ev, evc), (od, odc) = s["main_pair"]
        e, o = read_member(zips, ev, evc), read_member(zips, od, odc)
        with open(os.path.join(SIMROMS, f"{s['setname']}_maincpu.hex"), "w") as f:
            for i in range(len(e)):
                f.write(f"{(e[i] << 8) | o[i]:04x}\n")
        def bytes_hex(name, data):
            with open(os.path.join(SIMROMS, f"{s['setname']}_{name}.hex"), "w") as f:
                for b in data:
                    f.write(f"{b:02x}\n")
        bytes_hex("audiocpu", b"".join(read_member(zips, n, c) for n, c in s["audiocpu"]))
        bytes_hex("sprites", b"".join(read_member(zips, n, c) for n, c in s["sprites"]))
        if "view2_pair" in s:
            (ev, evc), (od, odc) = s["view2_pair"]
            a, b = read_member(zips, ev, evc), read_member(zips, od, odc)
            v = bytearray(2 * len(a)); v[0::2] = a; v[1::2] = b
        else:
            v = b"".join(read_member(zips, n, c) for n, c in s["view2_single"])
        bytes_hex("view2", v)
        bytes_hex("oki", b"".join(read_member(zips, n, c) for n, c in s["oki"]))
        print(f"wrote {s['setname']}_{{maincpu,audiocpu,sprites,view2,oki}}.hex into {os.path.relpath(SIMROMS, ROOT)}")


def main():
    argv = sys.argv[1:]
    names = [s["setname"] for s in SETS]
    if argv and argv[0] == "--check":
        sys.exit(0 if check() else 1)
    if argv and argv[0] == "--ioctl":
        ioctl(argv[1:] or names); return
    if argv and argv[0] == "--simroms":
        simroms(argv[1:] or names); return
    for s in SETS:
        write_mra(s)


if __name__ == "__main__":
    main()
